.Dd November 21, 2014
.Dt BASENAME 1 sbase\-VERSION
.Os
.Sh NAME
.Nm basename
.Nd strip leading path components
.Sh SYNOPSIS
.Nm basename
.Ar path
.Op Ar suffix
.Sh DESCRIPTION
.Nm
prints the
.Ar path
without leading path components and
.Ar suffix .
.Sh SEE ALSO
.Xr dirname 1 ,
.Xr basename 3
.Sh STANDARDS
The
.Nm
utility is compliant with the
.St -p1003.1-2008
specification.
