.TH CAL 1 sbase\-VERSION
.SH NAME
cal \- print calendar
.SH SYNOPSIS
.B cal
.RB [ \-1 ]
.RB [ \-3 ]
.RB [ \-m ]
.RB [ \-s ]
.RB [ \-y ]
.RB [ \-c
.IR columns ]
.RB [ \-f
.IR firstday ]
.RB [ \-n
.IR nmonths ]
.RB [ [ [
.IR day ]
.IR month ]
.IR year ]
.SH DESCRIPTION
Beginning with
.IR month
and
.IR year
print
.IR number
of calendars side by side. Each row of calendars contains at most
.IR columns
number of calendars. The defaults are obtained using
.IR localtime (3).
.SH OPTIONS
.TP
.B \-1
Print one single month.
.TP
.B \-3
Print prev/current/nexth month.
.TP
.B \-m
Print Monday as first day of week.
.TP
.B \-s
Print Sunday as first day of week.
.TP
.B \-y
Print a calendar of the current year.
.TP
.BI \-c " columns"
Print
.IR columns
number of calendars in a row. The default is 3.
.TP
.BI \-f " firstday"
Specify the first day of the week. 0 is Sunday and 6 is Saturday.
.TP
.BI \-n " nmonths"
Specify the number months to print. The default is 1.
.SH SEE ALSO
.IR localtime (3)
