.Dd January 18, 2015
.Dt CAL 1 sbase\-VERSION
.Sh NAME
.Nm cal
.Nd show calendar
.Sh SYNOPSIS
.Nm cal
.Op Fl 1 | Fl 3 | Fl y | Fl n Ar nmonths
.Op Fl s | Fl m | Fl f Ar firstday
.Op Fl c Ar columns
.Oo Oo Ar month Oc Ar year Oc
.Sh DESCRIPTION
Print
.Ar nmonths
calendars side by side beginning with
.Ar month
and
.Ar year .
Each row of calendars contains at most
.Ar columns
calendars. The date formatting is obtained using
.Xr localtime 3 .
.Pp
If
.Ar year
is given without
.Ar month ,
print the whole year, unless overridden by other options.
.Pp
The Julian calendar is used until Sep 2, 1752. The Gregorian calendar is used
starting the next day on Sep 14, 1752.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl 1
Output current month. This is the default.
.It Fl 3
Output previous, current and next month.
.It Fl n Ar nmonths
Output in total
.Ar nmonths
starting from the current month.
.It Fl y Ar year
Output an entire
.Ar year .
.It Fl s
Output Sunday as first day of week.
.It Fl m
Output Monday as first day of week.
.It Fl f Ar firstday
Output
.Ar firstday
(0 is Sunday, 6 is Saturday) as first day of week.
.It Fl c Ar columns
Set number of calendars in a row. The default is 3.
.El
.Sh SEE ALSO
.Xr localtime 3
.Sh STANDARDS
The
.Nm
utility is compliant with the
.St -p1003.1-2008
specification.
.Pp
The flags
.Op Fl 13ynsmfc
are an extension to that specification.
