.Dd February 9, 2015
.Dt CHGRP 1
.Os sbase
.Sh NAME
.Nm chgrp
.Nd change the file group ownership
.Sh SYNOPSIS
.Nm
.Op Fl R
.Op Fl H
.Op Fl L
.Op Fl P
.Ar groupname
.Op Ar file...
.Sh DESCRIPTION
.Nm
sets the group id of the files specified by
.Ar file
to the gid of the group named
.Ar group.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl R
Change file group ownership recursively.
.It Fl H
Only dereference symbolic links that are passed as command line arguments when
recursively traversing directories.
.It Fl L
Always dereference symbolic links while recursively traversing directories.
.It Fl P
Don't dereference symbolic links (default).
.Ar file .
.El
.Sh SEE ALSO
.Xr chmod 1 ,
.Xr chown 1 ,
.Xr chmod 2 ,
.Xr chown 2 ,
.Xr getgrnam 3
.Sh STANDARDS
The
.Nm
utility is compliant with the
.St -p1003.1-2008
specification except from the -h flag.
