.Dd January 30, 2015
.Dt CHGRP 1
.Os
.Sh NAME
.Nm chgrp
.Nd change the file group ownership
.Sh SYNOPSIS
.Nm
.Op Fl R
.Ar groupname
.Op Ar file...
.Sh DESCRIPTION
.Nm
sets the group id of the files specified by
.Ar file
to the gid of the group named
.Ar group.
If the
.Fl R
flag is specified, this process is recursively applied to
everything in
.Ar file .
.Sh SEE ALSO
.Xr chown 1 ,
.Xr chown 2 ,
.Xr chmod 1 ,
.Xr chmod 2 ,
.Xr getgrnam 3
