.TH CHMOD 1 sbase\-VERSION
.SH NAME
chmod \- change file mode
.SH SYNOPSIS
.B chmod
.RB [ \-Rr ]
.RI mode
.RI [ file ...]
.SH DESCRIPTION
.B chmod
changes the file mode for the given files.  The
.I mode
is a four digit octal number derived from its comprising bits.
.P
The first digit defines the setuid (4) and setgid (2) attributes.  The second
digit defines the owner's permissions: read (4), write (2), and execute (1); the
third defines permissions for others in the file's group; and the fourth for all
other users. Leading zeroes may be omitted.
.SH OPTIONS
.TP
.B \-R, \-r
change directory mode recursively.
.SH SEE ALSO
.IR chmod (2)
