.Dd February 17, 2015
.Dt CHOWN 1
.Os sbase
.Sh NAME
.Nm chown
.Nd change file ownership
.Sh SYNOPSIS
.Nm
.Op Fl h
.Oo
.Fl R
.Op Fl H | L | P
.Oc
.Op Ar owner Op Ar :group
.Op Ar file ...
.Sh DESCRIPTION
.Nm
changes the user or group ownership for the given
.Ar files .
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl h
Change the user ID and/or group ID of the symlink itself.  This flag cannot be used
with
.Op Fl R .
.It Fl R
Change directory ownership recursively.
.It Fl H
Only dereference symbolic links that are passed as command line arguments when
recursively traversing directories.
.It Fl L
Always dereference symbolic links while recursively traversing directories.
.It Fl P
Don't dereference symbolic links (default).
.El
.Sh SEE ALSO
.Xr chown 2
.Sh STANDARDS
The
.Nm
utility is compliant with the
.St -p1003.1-2008
specification.
