.Dd January 30, 2015
.Dt CHOWN 1
.Os sbase
.Sh NAME
.Nm chown
.Nd change file ownership
.Sh SYNOPSIS
.Nm
.Op Fl Rr
.Op Ar owner Op Ar :group
.Op Ar file ...
.Sh DESCRIPTION
.Nm
changes the user or group ownership for the given files.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl R
equivalent to \-r.
.It Fl r
change directory ownership recursively.
.El
.Sh SEE ALSO
.Xr chown 2
