.TH CHOWN 1 sbase\-VERSION
.SH NAME
chown \- change file ownership
.SH SYNOPSIS
.B chown
.RB [ \-r ]
.RI [ owner ][: group ]
.RI [ file ...]
.SH DESCRIPTION
.B chown
changes the user or group ownership for the given files.
.SH OPTIONS
.TP
.B \-r
change directory ownership recursively.
.SH SEE ALSO
.IR chown (2)
