.Dd January 30, 2015
.Dt CHROOT 1 sbase\-VERSION
.Os
.Sh NAME
.Nm chroot
.Nd invoke a command with a different root directory
.Sh SYNOPSIS
.Nm
.Ar dir
.Op Ar command Op Ar arg ...
.Sh DESCRIPTION
.Nm
runs
.Ar command
after changing the root directory to
.Ar dir
with the
.Xr chroot 2
system call, and changing the working directory to the new root.
If
.Op Ar command
is not specified, an interactive shell is started in the new root.
.Sh SEE ALSO
.Xr chdir 2 ,
.Xr chroot 2
