.TH CMP 1 sbase\-VERSION
.SH NAME
CMP \- compare two files
.SH SYNOPSIS
.B cmp
.RB [ \-ls ]
.RI file1
.RI file2
.SH DESCRIPTION
.B cmp
compares two files byte by byte. If the files differ, cmp prints the byte and
line number at which the difference occurred.
.P
The status code is 0 if the files are identical, and 1 if not.  If an error
occurred the status code is 2.
.SH OPTIONS
.TP
.B \-l
prints the byte number, and the differing bytes (in octal), for each difference.
.TP
.B \-s
prints nothing, only returns status.
.SH SEE ALSO
.IR comm (1),
.IR diff (1)
