.Dd March 22, 2014
.Dt COL 1
.Os sbase
.Sh NAME
.Nm col
.Nd filter reverse line-feeds
.Sh SYPNOSIS
.Nm
.Op Fl bfpx
.Op Fl l Ar num
.Sh DESCRIPTION
.Nm
filters all reverse (and half reverse) line feeds,
as produced by
.Xr nroff 1
with .2C,
.Xr ms 6
or
.Xr tbl 1 .
The recognized control sequences are:
.Bl -tag -width Ds
.It ESC-7
Reverse line-feed
.It ESC-8
Reverse half-line-feed
.It ESC-9
Forward half-line-feed
.It VT
Vertical-tab
.It SP
Space
.It TAB
Horizontal tab
.It RETURN
Carriage return
.It NL
New line
.El
.Pp
All other control codes and escape sequences are removed.
.Nm
converts all spaces to tabs.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl p
Print unknown escape sequences.
.It Fl b
Do not print backspaces and instead only print the last
character written to each column position.
.It Fl f
Allow forward half line feeds in the output.
.It Fl x
Do not convert spaces to tabs.
.It Fl l Ar num
Buffer
.Ar num
lines in memory. By default, 128 lines are buffered.
.El
.Sh SEE ALSO
.Xr nroff 1 ,
.Xr tbl 1 ,
.Xr ms 6
.Sh BUGS
.Nm
only buffers up to 128 lines with up to 800 bytes per line
if the line-number hasn't been set differently with the
.Op Fl l
flag.
When the number of lines is bigger, the buffer is flushed and
reverse line feeds can not operate on the flushed lines.
