.Dd January 30, 2015
.Dt CP 1
.Os
.Sh NAME
.Nm cp
.Nd copy files and directories
.Sh SYNOPSIS
.Nm
.Op Fl Rr
.Ar file
.Op Ar name
.Nm
.Op Fl aPpRrv
.Op Ar file ...
.Op Ar directory
.Sh DESCRIPTION
.Nm
copies a given file, naming it the given name. If multiple files are listed
they will be copied into the given directory.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl a
preserve mode, timestamp, links and permissions. Implies
.Fl d ,
.Fl p
and
.Fl r .
.It Fl P
don't dereference symbolic links.
.It Fl p
preserve mode, timestamp and permissions.
.It Fl f
if an existing destination file cannot be opened, remove it and try again.
.It Fl R
equivalent to -r.
.It Fl r
copies directories recursively. If this flag is not specified, directories
are not copied.
.It Fl v
print names of source and destination per file to stdout. In the format:
"source \-> destination".
.El
.Sh SEE ALSO
.Xr mv 1
