.Dd February 17, 2015
.Dt CP 1
.Os sbase
.Sh NAME
.Nm cp
.Nd copy files and directories
.Sh SYNOPSIS
.Nm
.Op Fl afpv
.Oo
.Fl R
.Op Fl H | L | P
.Oc
.Op Ar file ...
.Op Ar directory
.Sh DESCRIPTION
.Nm
copies a given
.Ar file ,
naming it the given
.Ar name .
If multiple
.Ar files
are listed
they will be copied into the given
.Ar directory .
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl a
Preserve mode, timestamp, links and permissions. Implies
.Fl d ,
.Fl p
and
.Fl r .
.It Fl f
If an existing destination file cannot be opened, remove it and try again.
.It Fl p
Preserve mode, timestamp and permissions.
.It Fl v
Print names of source and destination per file to stdout. In the format:
"source \-> destination".
.It Fl R
Copies directories recursively. If this flag is not specified, directories
are not copied.
.It Fl H
Only dereference symbolic links that are passed as command line arguments when
recursively traversing directories.
.It Fl L
Always dereference symbolic links while recursively traversing directories
(default).
.It Fl P
Don't dereference symbolic links.
.El
.Sh SEE ALSO
.Xr mv 1
