.TH DU 1 sbase\-VERSION
.SH NAME
du \- display disk usage statistics
.SH SYNOPSIS
.B du
.RB [ \-a
.RB |
.BR \-s ]
.RB [ \-d
.IR depth ]
.RB [ \-k ]
.RB [ \-h ]
.RI [ file ...]
.SH DESCRIPTION
.B du
displays the file system block usage for each
.I file
argument and for each directory in the file hierarchy rooted in directory argument.
If no file is specified, the block usage of the hierarchy rooted in the current
directory is displayed.
.SH OPTIONS
.TP
.BI \-a
Display an entry for each file in the file hierarchy.
.TP
.BI \-s
Display only the grand total for the specified files.
.TP
.BI "\-d depth"
Maximum directory depth to print files and directories.
.TP
.BI \-k
By default all sizes are reported in 512-byte block counts.
The -k option causes the numbers to be reported in kilobyte counts.
.TP
.BI \-h
Enable human readable output.
