.Dd January 25, 2015
.Dt HEAD 1
.Os sbase
.Sh NAME
.Nm head
.Nd display initial lines of files
.Sh SYNOPSIS
.Nm
.Op Fl n Ar num
.Op Fl N
.Op Ar file ...
.Sh DESCRIPTION
.Nm
writes
.Ar num
|
.Sy N
lines of each
.Ar file
to stdout.
If no file is given
.Nm
reads from stdin.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl n Ar num | Fl N
Display
.Ar num
|
.Sy N
lines. Default is 10.
.El
.Sh SEE ALSO
.Xr tail 1
.Sh STANDARDS
The
.Nm
utility is compliant with the
.St -p1003.1-2008
specification.
.Pp
The
.Op Fl N
flag is an extension to that specification.
