.TH HEAD 1 sbase\-VERSION
.SH NAME
head \- output first part of files
.SH SYNOPSIS
.B head
.RB [ \-n
.IR lines ]
.RI [ file ...]
.SH DESCRIPTION
.B head
writes the first 10 lines of each file to stdout.  If no file is given, head
reads from stdin.
.SH OPTIONS
.TP
.BI \-n " lines"
outputs the given number of lines.
.SH SEE ALSO
.IR tail (1)
