.Dd January 30, 2015
.Dt HOSTNAME 1 sbase\-VERSION
.Os
.Sh NAME
.Nm hostname
.Nd set or print name of current host system
.Sh SYNOPSIS
.Nm
.Op Ar name
.Sh DESCRIPTION
.Nm
sets or prints the name of the current host. If no argument is given,
the name of the current host is printed.
.Sh SEE ALSO
.Xr hostname 7
