.Dd November 23, 2014
.Dt KILL 1
.Os
.Sh NAME
.Nm kill
.Nd signal processes
.Sh SYNOPSIS
.Nm
.Op Fl s Ar signal_name
.Ar pid ...
.Nm
.Fl l Op Ar exit_status
.Nm
.Fl Ar signal_name
.Ar pid ...
.Nm
.Fl Ar signal_number
.Ar pid ...
.Sh DESCRIPTION
.Nm
by default sends a TERM signal to the given processes.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl s Ar signal_name
A symbolic signal name specifying the signal to be sent instead of the
default SIGTERM. Sends the named signal.
.It Fl l Op Ar exit_status
Lists available signals. If an
.Ar exit_status
is given, only the corresponding signal name will be printed.
.It Fl signal_name
A symbolic signal name specifying the signal to be sent instead
of the default SIGTERM.
.It Fl signal_number
A non-negative decimal integer specifying the signal to be sent instead of
the default SIGTERM.
.El
.Sh SEE ALSO
.Xr kill 2 ,
.Xr signal 7
.Sh STANDARDS
The
.Nm
utility is compliant with the
.St -p1003.1-2008
specification.
.Pp
The
.Fl Ar signal_name
and
.Fl Ar signal_number
syntax is marked by
.St -p1003.1-2008
as being an
X/OPEN System Interfaces
option.
