.TH KILL 1 sbase\-VERSION
.SH NAME
KILL \- signal processes
.SH SYNOPSIS
.B kill
.RB [ \-s
.IR signal ]
.RI [ pid ...]
.P
.B kill
.B -l
.RI [ signum ]
.SH DESCRIPTION
.B kill
sends a
.I TERM
signal to the given processes.
.SH OPTIONS
.TP
.BI \-s " signal"
sends the named signal.
.TP
.B \-l
lists available signals.  If a
.I signum
is given, only the corresponding signal name will be printed.
.SH SEE ALSO
.IR kill (2),
.IR signal (7)
