.TH KILL 1 sbase\-VERSION
.SH NAME
KILL \- signal processes
.SH SYNOPSIS
\fBkill\fR [ \fB-s\fR \fIsignal_name\fR ] \fIpid\fR \fI...\fR
.P
\fBkill\fR \fB-l\fR [ \fIexit_status\fR \fI...\fR]
.P
\fBkill\fR \fB-\fR\fIsignal_name\fR \fIpid\fR \fI...\fR
.P
\fBkill\fR \fB-\fR\fIsignal_number\fR \fIpid\fR \fI...\fR
.SH DESCRIPTION
.B kill
by default sends a
.I TERM
signal to the given processes.
.SH OPTIONS
.TP
.BI \-s " signal_name"
Sends the named signal.
.TP
.B \-l
Lists available signals.  If an
.I exit_status
is given, only the corresponding signal name will be printed.
.SH SEE ALSO
.IR kill (2),
.IR signal (7)
