.TH LN 1 sbase\-VERSION
.SH NAME
ln \- make links between files
.SH SYNOPSIS
.B ln
.RB [ \-LPfs ]
.I file
.RI [ name ]
.P
.B ln
.RB [ \-LPfs ]
.RI [ file ...]
.RI [ directory ]
.SH DESCRIPTION
.B ln
creates a hard link to a given file, with the given name.  If no name is given
it is linked into the current directory.  If multiple files are listed they will
be linked into the given directory.
.SH OPTIONS
.TP
.B \-L
create links to the files referenced by symbolic link source files (default
behavior).
.TP
.B \-P
create links to symbolic link source files themselves.
.TP
.B \-f
remove existing destinations.
.TP
.B \-s
create a symlink.
.SH SEE ALSO
.IR cp (1),
.IR link (2),
.IR symlink (2)
