.TH LN 1 sbase\-VERSION
.SH NAME
ln \- make links between files
.SH SYNOPSIS
.B ln
.RB [ \-fs ]
.I file
.RI [ name ]
.P
.B ln
.RB [ \-fs ]
.RI [ file ...]
.RI [ directory ]
.SH DESCRIPTION
.B ln
creates a hard link to a given file, with the given name.  If no name is given
it is linked into the current directory.  If multiple files are listed they will
be linked into the given directory.
.SH OPTIONS
.TP
.B \-f
remove existing destinations.
.TP
.B \-s
create a symlink.
.SH SEE ALSO
.IR cp (1),
.IR link (2),
.IR symlink (2)
