.Dd January 31, 2015
.Dt MD5SUM 1
.Os sbase
.Sh NAME
.Nm md5sum
.Nd compute or check MD5 checksums
.Sh SYNOPSIS
.Nm
.Op Fl c
.Op Ar file ...
.Sh DESCRIPTION
.Nm
writes an MD5 (128-bit) checksum of each
.Ar file
to stdout.
If no
.Ar file
is given
.Nm
reads from stdin.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl c
Read list of MD5 checksums from each
.Ar file
and check them.
.El
