.TH MKDIR 1 sbase\-VERSION
.SH NAME
mkdir \- make directory
.SH SYNOPSIS
.B mkdir
.RB [ \-p ]
.RI [ name ...]
.SH DESCRIPTION
.B mkdir
creates the specified directories.
.SH OPTIONS
.TP
.B \-p
creates any necessary parent directories, and does not fail if the target
already exists.
.SH SEE ALSO
.IR mkdir (2)
