.TH MKNOD 1 sbase\-VERSION
.SH NAME
mknod \- create a special device file

.SH SYNOPSIS
.B mknod
.RB [ \-m
.IR mode ]
.I name
.I type
.I major
.I minor

.SH DESCRIPTION
.B mknod
Creates a special device file named
.I name
with major number
.IR major ,
and minor number
.IR minor .

.IR type
specifies what kind of special file will be created,
and must be one of:
.TP
.BR u \ or\  c
A character device.
.TP
.BR b
A block device.

.SH OPTIONS
.TP
.B \-m "mode"
Set the mode of the new file based on the octal value of
.IR mode .

.SH SEE ALSO
.IR mknod (2)
