.Dd January 30, 2015
.Dt MKTEMP 1
.Os sbase
.Sh NAME
.Nm mktemp
.Nd create temporary file or directory
.Sh SYNOPSIS
.Nm
.Op Fl dq
.Op Ar template
.Sh DESCRIPTION
.Nm
creates a temporary file by generating a unique filename with
.Ar template ,
which has to have at least six 'X's appended to it.  If no
.Ar template
is specified, a default of 'tmp.XXXXXXXXXX' is used and the
tmpdir set to '/tmp' or, if set, the TMPDIR environment variable.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl d
create a temporary directory instead of a file.
.It Fl q
Fail silently if an error occurs.
.El
.Sh SEE ALSO
.Xr mkdtemp 3 ,
.Xr mkstemp 3
