.TH MV 1 sbase\-VERSION
.SH NAME
mv \- move files and directories
.SH SYNOPSIS
.B mv
.I file
.RI [ name ]
.P
.B mv
.RI [ file ...]
.RI [ directory ]
.SH DESCRIPTION
.B mv
moves or renames a given file or directory, naming it the given name.  If
multiple files and directories are listed they will be moved into the given
directory.
