.TH NICE 1 sbase\-VERSION
.SH NAME
nice \- invoke a utility with an altered nice value
.SH SYNOPSIS
.B nice
.RB [ \-n inc ]
.I command
.RI [ options ...]
.SH DESCRIPTION
.B nice
invokes
.IR command
with a nice value equal to the current nice value plus 
.IR inc, 
which defaults to 10 if unspecified.

.SH SEE ALSO
.IR renice (1) nice (2) 
