.TH NOHUP 1 sbase\-VERSION
.SH NAME
nohup \- run a command immune to hangups
.SH SYNOPSIS
.B nohup
.IR command ...
.SH DESCRIPTION
.B nohup
runs the given command with the
.I HUP
signal set to be ignored.  If stdout is a terminal, it is appended to
.I nohup.out
in the current working directory; if stderr is a terminal, it is redirected to
stdout.
.SH SEE ALSO
.IR signal (7)
