.Dd March 20, 2015
.Dt READLINK 1
.Os sbase
.Sh NAME
.Nm readlink
.Nd print symbolic link target or canonical file name
.Sh SYNOPSIS
.Nm
.Op Fl e | Fl f | Fl m
.Op Fl n
.Ar path
.Sh DESCRIPTION
.Nm
writes the target of
.Ar path ,
if it is a symbolic link, to stdout.
If not,
.Nm
exits with a non-zero return value.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl e | Fl f | Fl m
Canonicalize
.Ar name ,
which needn't be a symlink,
by recursively following every symlink in its path components.
All | All but the last | No path components must exist.
.It Fl n
Do not print the terminating newline.
.El
.Sh SEE ALSO
.Xr readlink 2 ,
.Xr realpath 3
