.TH RM 1 sbase\-VERSION
.SH NAME
rm \- remove files and directories
.SH SYNOPSIS
.B rm
.RB [ \-fr ]
.RI [ file ...]
.SH DESCRIPTION
.B rm
removes the given files and directories.
.SH OPTIONS
.TP
.B \-f
ignore files that cannot be removed.
.TP
.B \-r
remove directories recursively.
.SH SEE ALSO
.IR remove (3)
