.Dd January 30, 2015
.Dt SEQ 1
.Os sbase
.Sh NAME
.Nm seq
.Nd print a sequence of numbers
.Sh SYNOPSIS
.Nm
.Op Fl w
.Op Fl f Ar fmt
.Op Fl s Ar separator
.Op Ar start Op Ar step
.Ar end
.Sh DESCRIPTION
.Nm
will print a sequence of numbers from
.Ar start
(default: 1) to
.Ar end ,
in
.Ar step
intervals (default: 1).
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl f Ar format
Specifies the format used for output lines, as per
.Xr printf 3 .
.It Fl s Ar separator
Specifies the separator to print between output lines.
.It Fl w
Tells
.Nm
to print out lines in equal width.
.El
.Sh SEE ALSO
.Xr printf 3
