.TH SEQ 1 sbase\-VERSION
.SH NAME
seq \- print a sequence of numbers
.SH SYNOPSIS
.B seq 
.RB [ \-w ]
.RB [ \-f
.IR fmt ]
.RB [ \-s
.IR separator ]
.RI [ start
.RI [step] ]
.RI end
.SH DESCRIPTION
.B seq 
will print numbers from 
.I START
to
.I END,
in steps of
.I STEP. 
.SH OPTIONS
.TP
.BI \-f " format"
specifies the printf style for the output lines
.TP
.BI \-s " separator"
specifies the separator to print between output lines
.TP
.BI \-w
tells seq to print out lines in equal width
.TP

