.Dd January 30, 2015
.Dt SHA1SUM 1 sbase\-VERSION
.Os
.Sh NAME
.Nm sha1sum
.Nd compute SHA-1 message digest
.Sh SYNOPSIS
.Nm
.Op Fl c
.Op Ar file ...
.Sh DESCRIPTION
Print SHA-1 (160-bit) checksums. With no file, read standard input.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl c
read list of SHA1 checksums from file and check them
.El
