.Dd January 30, 2015
.Dt SORT 1
.Os
.Sh NAME
.Nm sort
.Nd sort lines
.Sh SYNOPSIS
.Nm
.Op Fl bnru
.Op Fl t Ar delim
.Op Fl k Ar key ...
.Op Ar file ...
.Sh DESCRIPTION
.Nm
writes the sorted concatenation of the given files to stdout. If no file is
given, sort reads from stdin.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl C
check that the concatenation of the given files is sorted rather than sorting
them. In this mode, no output is printed to stdout, and the exit status
indicates the result of the check.
.It Fl b
skip leading whitespace of columns when sorting.
.It Fl c
the same as
.Fl C
except that when disorder is detected, a message is printed to stderr
indicating the location of the disorder.
.It Fl k Ar key
specifies a key definition of the form
.Sm off
[.
.Sy s
][
.Sy f
][,
.Sy E
[.
.Sy e
][
.Sy f
]]
.Sm on
where
.Sm off
.Sy S
,
.Sy s
,
.Sy E
.Sm on
and
.Sy e
are the starting column, starting character in that column, ending column and
the ending character of that column respectively. If they are not specified,
.Sy s
refers to the first character of the specified starting column,
.Sy E
refers to the last column of every line, and
.Sy e
refers to the last character of that last column.
.Sy f
can be used to specify options
.Sm off
(
.Sy n
,
.Sy b
)
.Sm on
that only apply to this key definition.
.Sy b
is special in that it only applies to the column that it was specified after.
.It Fl n
perform a numeric sort.
.It Fl r
reverses the sort.
.It Fl t Ar delim
specifies the field delimiter.
.It Fl u
prints equal lines only once.
.El
