.TH NL 1 sbase\-VERSION
.SH NAME
sort \- sort lines
.SH SYNOPSIS
.B sort
.RB [ \-ru ]
.RI [ file ...]
.SH DESCRIPTION
.B sort
writes the sorted concatenation of the given files to stdout.  If no file is
given, sort reads from stdin.
.SH OPTIONS
.TP
.B \-r
reverses the sort.
.TP
.B \-u
prints repeated lines only once.
