.TH SPONGE 1 sbase\-VERSION
.SH NAME
sponge \- soak up standard input and write to a file
.SH SYNOPSIS
.B sponge
.IR file
.SH DESCRIPTION
.B sponge
reads stdin completely, then writes the saved contents to
.IR file .
This makes it possible to easily create pipes which read from and write to
the same file.

If the given file is a symbolic link, it writes to the links's destination
instead.
