.Dd January 30, 2015
.Dt SPONGE 1
.Os
.Sh NAME
.Nm sponge
.Nd soak up standard input and write to a file
.Sh SYNOPSIS
.Nm
.Ar file
.Sh DESCRIPTION
.Nm
reads stdin completely, then writes the saved contents to
.Ar file .
This makes it possible to easily create pipes which read from and write to
the same file.
.Pp
If the given file is a symbolic link, it writes to the links destination
instead.
