.Dd November 23, 2014
.Dt STRINGS 1
.Os sbase
.Sh NAME
.Nm strings
.Nd print the strings of pritable characters in files
.Sh SYNOPSIS
.Nm
.Op Ar file ...
.Sh DESCRIPTION
.Nm
prints the printable character sequences that are at least 6 characters
long. If no
.Ar files
are given,
.Nm
reads from stdin.
.Sh STANDARDS
.Nm
mirrors the semantics of Plan9
.Xr strings 1 .
