.Dd November 23, 2014
.Dt STRINGS 1
.Os sbase
.Sh NAME
.Nm strings
.Nd print the strings of printable characters in files
.Sh SYNOPSIS
.Nm
.Op Fl a
.Op Ar file ...
.Sh DESCRIPTION
.Nm
prints the printable character sequences that are at least 6 characters
long. If no
.Ar files
are given,
.Nm
reads from stdin.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl a
Scan files in their entirety. This is the default.
.El
.Sh STANDARDS
.Nm
mirrors the semantics of Plan9
.Xr strings 1 .
