.Dd November 23, 2014
.Dt STRINGS 1 sbase\-VERSION
.Os
.Sh NAME
.Nm strings
.Nd print the strings of pritable characters in files
.Sh SYNOPSIS
.Nm strings
.Op Ar file ...
.Sh DESCRIPTION
.Nm
prints the printable character sequences that are at least 6 characters
long.  If no files are given then it uses stdin.
.Sh STANDARDS
.Nm
mirrors the semantics of Plan9
.Xr strings 1 .
