.Dd February 9, 2015
.Dt TAIL 1
.Os sbase
.Sh NAME
.Nm tail
.Nd display final lines of files
.Sh SYNOPSIS
.Nm
.Op Fl f
.Op Fl n Ar num
.Op Ar file ...
.Sh DESCRIPTION
.Nm
writes the last 10 lines of each
.Ar file
to stdout. If no
.Ar file
is given,
.Nm
reads from stdin.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl f
If one
.Ar file
is specified, append lines to output as
.Ar file
grows.
.It Fl n Ar lines
Display
.Ar num
lines. If
.Ar num
begins with '+' it is used as an offset from the beginning of each
.Ar file .
.El
.Sh SEE ALSO
.Xr head 1
