.Dd January 31, 2015
.Dt TAR 1
.Os
.Sh NAME
.Nm tar
.Nd create, list or extract a tape archive
.Sh SYNOPSIS
.Nm
.Op Fl C Ar dir
.Op Fl jz
.Fl x Op Fl m
|
.Fl t
.Op Fl f Ar tarfile
.Nm
.Op Fl C Ar dir
.Op Fl jz
.Fl c Ar dir
.Op Fl f Ar tarfile
.Nm
.Op Fl C Ar dir
.Op Fl jz
.Fl cf
.Ar tarfile Ar dir
.Sh DESCRIPTION
.Nm
is the standard file archiver. Generally the archives
created with it are further compressed.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl c Ar path
Creates tarball from
.Ar path .
.It Fl C Ar dir
Change directory to
.Ar dir
before beginning.
.It Fl f Ar tarfile
Make
.Ar tarfile
be the archive, rather than stdin or stdout.
.It Fl j
Compress archive using bzip2. The
.Xr bzip2 1
utility must be installed separately.
.It Fl m
Do not preserve modification time.
.It Fl t
List all files in tarball.
.It Fl x
Extract tarball.
.It Fl z
Compress archive using gzip. The
.Xr gzip 1
utility must be installed separately.
.El
.Sh SEE ALSO
.Xr ar 1 ,
.Xr bzip2 1 ,
.Xr gzip 1
