.TH TEE 1 sbase\-VERSION
.SH NAME
tee \- duplicate stdin
.SH SYNOPSIS
.B tee
.RB [ \-ai ]
.RI [ file ...]
.SH DESCRIPTION
.B tee
writes from stdin to stdout, making copies in each file.
.SH OPTIONS
.TP
.B \-a
append to each file rather than overwriting.
.TP
.B \-i
ignore SIGINT, i.e. the interrupt from keyboard signal
