.Dd February 9, 2015
.Dt TOUCH 1
.Os sbase
.Sh NAME
.Nm touch
.Nd set file timestamps
.Sh SYNOPSIS
.Nm
.Op Fl acm
.Op Fl r Ar ref_file | t Ar timestamp
.Ar file ...
.Sh DESCRIPTION
.Nm
sets the access or modification time of each
.Ar file
to the current time of day. If
.Ar file
doesn't exist, it is created with default permissions.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl a | Fl m
Set the access | modification time of
.Ar file.
.It Fl c
Don't create
.Ar file
if it doesn't exist, not affecting exit status.
.It Fl r Ar ref_file
Set the timestamp
to be used with
.Op Fl am
to the modification time of
.Ar ref_file .
.It Fl t Ar timestamp
Set the
.Ar timestamp
to be used with
.Op Fl am
given as the number of seconds since the
Unix epoch 1970-01-01T00:00:00Z.
.El
.Sh SEE ALSO
.Xr date 1
.Sh STANDARDS
The
.Nm
utility is compliant with the
.St -p1003.1-2008
specification except from the
.Ar timestamp
format of the
.Fl t
flag.
