.Dd January 20, 2014
.Dt TOUCH 1
.Os
.Sh NAME
.Nm touch
.Nd set file timestamps
.Sh SYNOPSIS
.Nm
.Op Fl acm
.Op Fl t Ar stamp
.Ar file ...
.Sh DESCRIPTION
.Nm
sets the access and modification times of files to the current time of day.  If the file
doesn't exist, it is created with the default permissions.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl a
Set the access time of the file.
.It Fl c
Do not create the file it it does not exist.  The exit
status is not affected.
.It Fl m
Change the modification time of the file.
.It Fl t Ar stamp
Set the timestamp to be used with
.Op Fl am .
The format of the timestamp is simply the number of seconds
since Jan 1, 1970.  This specification of time does not conform
to POSIX.
.El
.Sh SEE ALSO
.Xr date 1
