.Dd January 30, 2015
.Dt TTY 1 sbase\-VERSION
.Os
.Sh NAME
.Nm tty
.Nd print terminal name
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
prints the name of the terminal open on stdin.
.Pp
The status code is 0 if stdin is a terminal, and 1 if not. If an error occurred
the status code is 2.
.Sh SEE ALSO
.Xr ttyname 3
