.TH UNAME 1 sbase\-VERSION
.SH NAME
uname \- print system information
.SH SYNOPSIS
.B uname
.RB [ \-amnrsv ]
.SH DESCRIPTION
.B uname
prints system information.  If no flags are given, uname will print only the
name of the operating system
.RB ( \-s ).
.SH OPTIONS
.TP
.B \-a
print all the information below.
.TP
.B \-m
print the machine's architecture.
.TP
.B \-n
print the system's network name.
.TP
.B \-r
print the operating system's release name.
.TP
.B \-s
print the name of the operating system.
.TP
.B \-v
print the operating system's version name.
.SH SEE ALSO
.IR uname (2)
