.Dd January 30, 2015
.Dt UNAME 1
.Os sbase
.Sh NAME
.Nm uname
.Nd print system information
.Sh SYNOPSIS
.Nm
.Op Fl amnrsv
.Sh DESCRIPTION
.Nm
prints system information. If no flags are given,
.Nm
will print only the
name of the operating system as
.Fl s
would.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl a
Print all the information below.
.It Fl m
Print the machine's architecture.
.It Fl n
Print the system's network name.
.It Fl r
Print the operating system's release name.
.It Fl s
Print the name of the operating system.
.It Fl v
Print the operating system's version name.
.El
.Sh SEE ALSO
.Xr uname 2
