.Dd January 30, 2015
.Dt WC 1
.Os
.Sh NAME
.Nm wc
.Nd word count
.Sh SYNOPSIS
.Nm
.Op Fl clmw
.Op Ar file ...
.Sh DESCRIPTION
.Nm
.Pp
prints the number of lines, words, and bytes in each file.  If any flags are
given, wc will print only the requested information.  If no files are given, wc
reads stdin.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl c
print the number of bytes.
.It Fl l
print the number of lines.
.It Fl m
print the number of characters, not bytes.
.It Fl w
print the number of words.
.El
