.Dd January 30, 2015
.Dt XARGS 1
.Os sbase
.Sh NAME
.Nm xargs
.Nd construct argument list(s) and execute command
.Sh SYNOPSIS
.Nm
.Op Fl n Ar maxargs
.Op Fl r
.Op Fl E Ar eofstr
.Op Ar cmd Op Ar arg...
.Sh DESCRIPTION
.Nm
reads space, tab, newline and EOF delimited strings from stdin
and executes the specified
.Ar cmd
with the strings as
.Ar arguments .
.Pp
Any arguments specified on the command line are given to the command upon
each invocation, followed by some number of the arguments read from
stdin. The command is repeatedly executed one or more times until stdin
is exhausted.
.Pp
Spaces, tabs and newlines may be embedded in arguments using single (`'')
or double (`"') quotes or backslashes ('\\').  Single quotes escape all
non-single quote characters, excluding newlines, up to the matching single
quote.  Double quotes escape all non-double quote characters, excluding
newlines, up to the matching double quote.  Any single character, including
newlines, may be escaped by a backslash.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl n Ar maxargs
Use at most
.Ar maxargs
arguments per command line.
.It Fl r
Do not run the command if there are no arguments.  Normally the command is
executed at least once even if there are no arguments.
.It Fl E Ar eofstr
Use
.Ar eofstr
as a logical EOF marker.
.El
.Sh EXIT STATUS
xargs exits with one of the following values:
.Bl -tag -width Ds
.It 0
All invocations of command returned a zero exit status.
.It 123
One or more invocations of command returned a nonzero exit status.
.It 124
The command exited with a 255 exit status.
.It 125
The command was killed or stopped by a signal.
.It 126
The command was found but could not be executed.
.It 127
The command could not be found.
.It 1
Some other error occurred.
.El
